let documentFontStylesPromise: Promise<unknown[]> | undefined;

/** Load document-only browser faces when the editor is activated. The PDF
 * bundle remains independent and is still loaded only for export. */
export function loadDocumentFontStyles(): Promise<unknown[]> {
  documentFontStylesPromise ??= Promise.all([
    import("@fontsource/source-sans-3/400.css"),
    import("@fontsource/source-sans-3/600.css"),
    import("@fontsource/source-sans-3/700.css"),
    import("@fontsource/source-sans-3/400-italic.css"),
    import("@fontsource/source-sans-3/600-italic.css"),
    import("@fontsource/source-sans-3/700-italic.css"),
    import("@fontsource/source-serif-4/400.css"),
    import("@fontsource/source-serif-4/600.css"),
    import("@fontsource/source-serif-4/700.css"),
    import("@fontsource/source-serif-4/400-italic.css"),
    import("@fontsource/source-serif-4/600-italic.css"),
    import("@fontsource/source-serif-4/700-italic.css"),
    import("@fontsource/stix-two-text/400.css"),
    import("@fontsource/stix-two-text/600.css"),
    import("@fontsource/stix-two-text/700.css"),
    import("@fontsource/stix-two-text/400-italic.css"),
    import("@fontsource/stix-two-text/600-italic.css"),
    import("@fontsource/stix-two-text/700-italic.css"),
    import("@fontsource/atkinson-hyperlegible/400.css"),
    import("@fontsource/atkinson-hyperlegible/700.css"),
    import("@fontsource/atkinson-hyperlegible/400-italic.css"),
    import("@fontsource/atkinson-hyperlegible/700-italic.css"),
    import("@fontsource/ibm-plex-sans/400.css"),
    import("@fontsource/ibm-plex-sans/600.css"),
    import("@fontsource/ibm-plex-sans/700.css"),
    import("@fontsource/ibm-plex-sans/400-italic.css"),
    import("@fontsource/ibm-plex-sans/600-italic.css"),
    import("@fontsource/ibm-plex-sans/700-italic.css"),
    import("@fontsource/ibm-plex-serif/400.css"),
    import("@fontsource/ibm-plex-serif/600.css"),
    import("@fontsource/ibm-plex-serif/700.css"),
    import("@fontsource/ibm-plex-serif/400-italic.css"),
    import("@fontsource/ibm-plex-serif/600-italic.css"),
    import("@fontsource/ibm-plex-serif/700-italic.css"),
    import("@fontsource/lato/400.css"),
    import("@fontsource/lato/700.css"),
    import("@fontsource/lato/400-italic.css"),
    import("@fontsource/lato/700-italic.css"),
    import("@fontsource/merriweather/400.css"),
    import("@fontsource/merriweather/600.css"),
    import("@fontsource/merriweather/700.css"),
    import("@fontsource/merriweather/400-italic.css"),
    import("@fontsource/merriweather/600-italic.css"),
    import("@fontsource/merriweather/700-italic.css"),
    import("@fontsource/noto-sans/400.css"),
    import("@fontsource/noto-sans/600.css"),
    import("@fontsource/noto-sans/700.css"),
    import("@fontsource/noto-sans/400-italic.css"),
    import("@fontsource/noto-sans/600-italic.css"),
    import("@fontsource/noto-sans/700-italic.css"),
    import("@fontsource/noto-serif/400.css"),
    import("@fontsource/noto-serif/600.css"),
    import("@fontsource/noto-serif/700.css"),
    import("@fontsource/noto-serif/400-italic.css"),
    import("@fontsource/noto-serif/600-italic.css"),
    import("@fontsource/noto-serif/700-italic.css"),
    import("@fontsource/roboto-mono/400.css"),
    import("@fontsource/roboto-mono/600.css"),
    import("@fontsource/roboto-mono/700.css"),
    import("@fontsource/roboto-mono/400-italic.css"),
    import("@fontsource/roboto-mono/600-italic.css"),
    import("@fontsource/roboto-mono/700-italic.css")
  ]);
  return documentFontStylesPromise;
}
