"""Render and validate the planning data. Does not create or alter scientific artwork."""
from pathlib import Path
import json, re, hashlib, csv, collections, subprocess, unicodedata
ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'docs/scientific-asset-planning'
BASE = 'f76212775d0fc1af43c7079964b5d22cfecf6324'
DATE = '2026-09-05'
def norm(s):
    s=unicodedata.normalize('NFKD',s).casefold().replace('α','alpha').replace('β','beta').replace('γ','gamma')
    return re.sub(r'[^a-z0-9]+',' ',s).strip()
def dump(path,obj): path.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
S=[]
def source(key,title,url,location,claim,kind='official curated scientific resource'):
    S.append(dict(source_id=key,title=title,url=url,evidence_location=location,verified_scope=claim,artifact_type=kind,accessed_date=DATE,evidence_state='reported',retrieval='Opened source text using web tool; no source artwork downloaded.'))
source('TCR','TCR signaling','https://reactome.org/content/detail/R-HSA-202403','Summary and Events: Phosphorylation of CD3; Translocation of ZAP-70','TCR/CD3 engagement couples to tyrosine kinases and adaptor phosphorylation.')
source('BCR','Signaling by the B Cell Receptor (BCR)','https://reactome.org/content/detail/R-HSA-983705','Summary paragraphs 1-7','Antigen recognition by membrane immunoglobulin activates CD79 ITAMs, SYK and downstream second messengers.')
source('C3','Complement cascade','https://reactome.org/content/detail/R-HSA-166658','Summary: convergence, outcomes and nomenclature note','Three initiation routes converge on C3 cleavage; opsonization, inflammation and terminal pore formation are distinct outputs.')
source('PLT','Platelet activation, signaling and aggregation','https://reactome.org/content/detail/R-HSA-76002','Summary and Events: Platelet Aggregation','Adhesion and agonists trigger platelet activation; released agonists amplify recruitment and aggregation.')
source('AUTO','Macroautophagy','https://reactome.org/content/detail/R-HSA-1632852','Summary: isolation membrane, autophagosome and autolysosome','A phagophore encloses cargo, seals as an autophagosome and delivers cargo to lysosomes.')
source('WNT','Signaling by WNT','https://reactome.org/content/detail/R-HSA-195721','Summary: canonical pathway and context dependence','Canonical WNT stabilizes beta-catenin for nuclear transcriptional coactivation; noncanonical responses depend on context.')
source('MHCI','Antigen Presentation: Folding, assembly and peptide loading of class I MHC','https://reactome.org/content/detail/R-HSA-983170','Summary and Events: transport into ER, loading and surface transport','Peptides load onto class I MHC in the ER; stable complexes travel through Golgi to the surface.')
source('MHCII','MHC class II antigen presentation','https://reactome.org/content/detail/R-HSA-2132295','Summary and Events: invariant chain, antigen processing and loading','Endocytic antigen processing and class II loading precede surface presentation to CD4 T cells.')
source('IGE','Fc epsilon receptor (FCERI) signaling','https://reactome.org/content/detail/R-HSA-2454202','Summary and Events: IgE binding, aggregation and degranulation','Allergen-dependent aggregation of IgE-bound Fc receptors drives mast-cell signaling and mediator release.')
source('PD1','Co-inhibition by PD-1','https://reactome.org/content/detail/R-HSA-389948','Summary and Events: ligation and phosphatase recruitment','Ligated PD-1 recruits phosphatases and attenuates T-cell signaling.')
source('IFN','Interferon alpha/beta signaling','https://reactome.org/content/detail/R-HSA-909733','Summary and Events: receptor assembly, JAKs, STATs and ISGF3','Type I interferons signal through IFNAR1/2; STAT1, STAT2 and IRF9 form ISGF3.')
source('NOTCH','Signaling by NOTCH1','https://reactome.org/content/detail/R-HSA-1980143','Summary paragraphs 1-3','A neighboring membrane ligand triggers NOTCH1 cleavage and nuclear NICD-dependent transcription.')
source('APOP','Intrinsic Pathway for Apoptosis','https://reactome.org/content/detail/R-HSA-109606','Summary and Events: BAX/BAK and apoptotic factor response','BCL-2-family regulation links intracellular stress to mitochondrial disruption and downstream apoptosis.')
source('FERR','Ferritin and Transferrin','https://pdb101.rcsb.org/motm/35','Storing Iron; Transferrin and transferrin receptor','Ferritin encloses stored iron; transferrin carries iron and cycles through acidified endosomes with its receptor.')
source('FIB','Fibrin','https://pdb101.rcsb.org/motm/83','Building a Scab; Flexible Fibrin; assembly discussion','Thrombin cleavage converts soluble fibrinogen into fibrin that assembles into fibers.')
source('NANO','Nanodiscs and HDL','https://pdb101.rcsb.org/motm/237','Introductory description; Good Cholesterol; Exploring the Structure','A stabilizing protein belt surrounds a small lipid bilayer disc; nanodiscs support membrane-protein studies.')
source('RIBO','Riboswitches','https://pdb101.rcsb.org/motm/130','Self Control; Flipping the Switch','Ligand binding stabilizes an RNA conformation that changes transcription or translation; response direction varies.')
source('TELO','Telomerase','https://pdb101.rcsb.org/motm/227','Protecting the Ends; Add Six Bases, Repeat; Quadruplexes','Telomerase uses an RNA template to extend telomeric DNA; guanine-rich DNA can form quadruplexes.')
source('LPS','Making Lipopolysaccharide','https://pdb101.rcsb.org/learn/structural-biology-highlights/making-lipopolysaccharide','Introduction; Lipid Carrier','LPS combines lipid anchors with carbohydrate regions; carbohydrate composition varies among bacteria.')
source('GUT','Small Intestine','https://histology.leeds.ac.uk/home/digestive/small_intestine/','Structure; Epithelium and Villi; Crypts','Villi, microvilli and crypts organize absorptive and secretory epithelial functions; Paneth cells occupy crypt bases.','institutional teaching reference')
source('CAP','Capillaries','https://histology.leeds.ac.uk/home/circulatory/capillaries/','Continuous; Fenestrated capillaries; Sinusoids','Capillary endothelial architectures differ; pericytes are associated with continuous capillaries.','institutional teaching reference')
source('LUNG','Respiratory portion','https://histology.leeds.ac.uk/home/respiratory/respiratory/','Alveoli; Main constituents of alveolus and interalveolar wall','Flattened type I and secretory type II pneumocytes have different roles at the alveolar gas-exchange surface.','institutional teaching reference')
source('PORIN','Porins','https://pdb101.rcsb.org/global-health/antimicrobial-resistance/drugs/antibiotic-resistance-mechanisms/porins','Normal Function; Types; Structure; Resistance Due to Decreased Permeability','Bacterial porins provide outer-membrane diffusion channels; reduced permeability can contribute to antibiotic resistance.')
source('HJ','Effect of Sequence on the Conformational Geometry of DNA Holliday Junctions','https://www.rcsb.org/structure/1P4Y','Primary Citation abstract; structure metadata','This deposited DNA forms four-way stacked-X junctions; junction geometry is sequence dependent.','primary structural deposition')
source('IGEF','The crystal structure of IgE Fc reveals an asymmetrically bent conformation','https://www.rcsb.org/structure/1O0V','Primary Citation abstract','IgE Fc has an extra C-epsilon-2 domain pair relative to the IgG hinge and a bent structure in this entry.','primary structural deposition')
source('AGG','Nanomechanics of Aggrecan: A New Perspective on Cartilage Biomechanics, Disease and Regeneration','https://www.ncbi.nlm.nih.gov/books/NBK604357/','Abstract; Structure of Aggrecan; Nanomechanics sections','Aggrecan is a core protein carrying glycosaminoglycan chains; its organization contributes to cartilage mechanics.','scholarly book chapter hosted by NCBI')
source('SPLICE','mRNA Splicing - Major Pathway','https://reactome.org/content/detail/R-HSA-72163','Summary paragraphs 1-6','Spliceosomal reactions generate an intron lariat and join the flanking exons.')
source('INS','Insulin receptor signalling cascade','https://reactome.org/content/detail/R-HSA-74751','Summary and Events: SHC, IRS and attenuation','Insulin-receptor autophosphorylation recruits signaling pathways and receptor internalization attenuates signaling.')
source('CLONE','Plasmid Cloning by Restriction Enzyme Digest','https://www.addgene.org/protocols/subcloning/','Design; Digest; Ligate; Transform; Isolate the Finished Plasmid','Compatible ends and orientation matter in restriction cloning; colony recovery alone does not verify the construct.','official method documentation')
source('GIBSON','Gibson Assembly Protocol','https://www.addgene.org/protocols/gibson-assembly/','Procedure: design and enzyme functions','Overlapping fragments are joined using exonuclease, polymerase and ligase activities.','official method documentation')
source('GOLD','Golden Gate Assembly','https://www.neb-online.de/en/cloning-synthetic-biology/dna-assembly/golden-gate-assembly/','Overview and Golden Gate Assembly workflow','Type IIS cleavage outside recognition sites produces designed overhangs for ordered ligation.','official method documentation')
source('ATAC','Getting Started: Single Cell ATAC','https://www.10xgenomics.com/support/epi-atac/documentation/steps/experimental-design-and-planning/getting-started-single-cell-atac','Introduction','The described assay transposes nuclei in bulk before partitioning and associates reads with partition barcodes.','official method documentation')
source('FEATURE','What is Feature Barcode?','https://www.10xgenomics.com/support/software/cell-ranger/10.0/getting-started/cr-what-is-feature-bc','Feature Barcode technology and application bullets','Antibody oligos, captured CRISPR guides and sample tags add distinct information to single-cell gene expression.','official method documentation')
source('ANNEX','Annexin V Staining','https://www.thermofisher.com/dk/en/home/life-science/cell-analysis/cell-viability-and-regulation/apoptosis/annexin-v-staining.html','What is Annexin V; How Annexin V staining works; false-positive caveat','Annexin V binds phosphatidylserine in a calcium-dependent manner; membrane damage complicates interpretation.','official method documentation')
source('STING','STING mediated induction of host immune responses','https://reactome.org/content/detail/R-HSA-1834941','Summary: ER localization, trafficking and TBK1/IRF3','Activated STING changes localization and recruits TBK1/IRF3 signaling; the page mixes historical human and mouse evidence.')

R=[]
def record(id,kind,name,category,fact,design,components,states,caution,sources,novelty,related='',priority='P2'):
    R.append(dict(id=id,kind=kind,name=name,category=category,scientific_description=fact,design_instructions=design,component_names=components.split(';') if components else [],states=states.split(';'),scientific_caveat=caution,source_ids=sources.split(';'),novelty=novelty,related_baseline=related,priority=priority,verification='source_checked_schematic',design_status='proposed_not_generated'))
def a(id,name,cat,fact,design,components,states,caution,sources,related): record(id,'new_primitive',name,cat,fact,design,components,states,caution,sources,'new',related)
def p(id,name,cat,fact,design,components,states,caution,sources,related=''): record(id,'reuse_preset',name,cat,fact,design,components,states,caution,sources,'reuse',related)
def c(id,name,cat,fact,design,components,states,caution,sources,related='',priority='P2'): record(id,'composite',name,cat,fact,design,components,states,caution,sources,'roadmap_expansion' if related.startswith('roadmap:') else ('baseline_expansion' if related else 'new'),related,priority)

# Distinct building blocks. These are requests for future work, not generated assets.
a('A001','Ferritin protein cage','Proteins','Ferritin provides a hollow protein shell for iron storage.','Plan an intact sphere and a cutaway of the same shell. Keep the cavity, shell and optional iron-core overlay separately addressable. Use a cage silhouette rather than the open tunnel of a chaperonin; do not prescribe atomic surface detail.','generic globular protein','empty;iron-loaded;cutaway','A schematic shell does not establish a species-specific subunit composition. Resolve an exact structure before showing numbered subunits.','FERR','Closest baseline: ring-shaped protein complex and chaperonin barrel; neither is a closed storage cage.')
a('A002','Fibrinogen monomer','Extracellular matrix','Soluble fibrinogen is cleaved to produce fibrin, which can assemble into fibers.','Use an elongated molecule with a central region and two distal lobes connected by slender arms. Provide removable cleavage-site annotations and end attachment points so copies can later form a fiber. Keep the soluble precursor separate from the assembled network.','fibrin fiber','intact;cleavage annotations;assembly-ready','Flexible regions are not completely resolved in many structures. Avoid treating the drawing as exact molecular geometry.','FIB','Closest baseline: fibrin fiber, which represents the polymer rather than soluble precursor.')
a('A003','Lipopolysaccharide molecule','Microbiology','LPS connects a lipid anchor to carbohydrate regions on Gram-negative bacterial surfaces.','Provide a lipid-anchor module beneath an editable sugar-chain region. Mark membrane insertion and extracellular chain endpoints. Offer schematic short-chain and extended-chain states with strain identity left unset.','phospholipid','short carbohydrate;extended carbohydrate;membrane-anchored','Do not infer a fixed sugar sequence, tail count or universal O-antigen length from a generic LPS symbol.','LPS','Closest baseline: glycocalyx and phospholipid; a single LPS building block has a distinct composite molecular architecture.')
a('A004','IgE Fc domain module','Immunology','IgE Fc contains a C-epsilon-2 domain pair and can adopt a bent configuration distinct from IgG Fc.','Design an Fc-only module with paired domain regions and two Fab attachment anchors. Preserve a bent silhouette and expose the receptor-binding side. Full IgE must later reuse two library Fab fragments with this module.','antibody Fab fragment','unbound schematic;receptor-bound placeholder','The cited structure contains Fc, not complete IgE; it does not establish the bound whole-antibody geometry.','IGEF','Closest baseline: antibody Fc fragment and generic IgG antibody; do not relabel IgG Fc as structurally detailed IgE.')
a('A005','Bacterial porin beta-barrel','Microbiology','Classical porins provide water-filled diffusion paths through the bacterial outer membrane.','Plan a short membrane-spanning barrel with a visible lumen and rim loops. Supply side and axial views with separate lumen and membrane anchors. Assemble oligomers from instances; label the selected porin before giving an oligomer count.','transmembrane protein','side view;axial view;restricted lumen','Porins vary in selectivity and oligomeric organization. Do not turn the archetype into a universal ATP-driven transporter.','PORIN','Closest baseline: ligand-gated ion channel and solute carrier transporter; beta-barrel outer-membrane architecture differs.')
a('A006','Aggrecan proteoglycan monomer','Extracellular matrix','Aggrecan has glycosaminoglycan side chains attached to a protein core.','Plan a flexible core with detachable brush-like side chains and a designated attachment region. Preserve chain/core separation for intact and fragmented states. A cartilage panel must assemble these with existing collagen and cell assets.','collagen fibril','intact;reduced side chains;fragmented','This is an aggrecan archetype, not the architecture of every proteoglycan; no quantitative stiffness follows from chain density in the icon.','AGG','Closest baseline: extracellular matrix mesh and collagen fibril; neither represents a single decorated proteoglycan.')
a('A007','Membrane scaffold protein belt','Structural biology','Engineered scaffold proteins stabilize the edge of a nanodisc lipid bilayer.','Plan a reusable open/closed belt around a circular or elliptical membrane boundary, with lipid-facing inner edge and exposed outer edge. Build the disc from existing lipid bilayer components and this belt rather than baking a membrane protein into it.','lipid bilayer cross-section','open belt;closed belt;side view','Disc dimensions and belt stoichiometry depend on the scaffold construct. No single size is implied.','NANO','Closest baseline: coiled-coil protein and ring-shaped protein complex; a lipid-edge scaffold has a different assembly role.')
a('A008','G-quadruplex topology module','Nucleic acids','Guanine-rich nucleic acid can fold into quadruplex structures.','Plan a strand-followable stack of tetrad placeholders with connecting loops. Retain 5-prime and 3-prime anchors. Use a compact topology view and a simplified small-scale icon; reserve base and ion labels for a specified structure.','single-stranded DNA','folded;unfolded comparison','Loop topology and strand orientation are sequence dependent. A telomere need not be folded into this state.','TELO','Closest baseline: DNA double helix and telomere; neither conveys four-stranded folding.')
a('A009','Four-way DNA junction topology module','Nucleic acids','Holliday junctions connect four DNA arms; their conformation depends on sequence and conditions.','Plan four duplex arms with continuous colored strand paths through the junction. Include an explanatory open layout and a compact stacked arrangement. Crossing strands must remain traceable and must not appear severed.','DNA double helix','open schematic;stacked schematic','Open layout is an explanatory design choice. The cited deposition directly supports a stacked-X conformation, not a universal angle.','HJ','Closest baseline: replication fork has three arms; a four-way junction adds a different topology.')
a('A010','Pericyte with vessel-facing processes','Cells','Pericytes are associated with the outside of capillary endothelium.','Plan an elongated nucleated cell whose processes can follow a vessel exterior. Provide a vessel-contact anchor and process handles. Keep the vessel itself separate and leave marker labels optional.','endothelial cell','isolated;vessel-associated orientation','Shape varies by vascular bed. Positioning outside the endothelial lumen is the verified constraint; process lengths are schematic.','CAP','Closest baseline: smooth muscle cell and fibroblast; the vascular wrapping configuration should remain distinguishable.')
a('A011','Paneth cell with apical granule compartment','Cells','Paneth cells occur at intestinal crypt bases and contain antimicrobial secretory granules.','Plan a crypt-compatible epithelial outline with a distinct granule-rich apical region and basal nucleus. Include explicit apical/basal anchors so the cell can be inserted among existing epithelial cells. Keep granules separate for a secretion scene.','columnar epithelial cell;secretory vesicle','granule-rich;secretion-ready','Granule colors are design choices, not unstained biological colors. Do not identify all granular epithelial cells as Paneth cells.','GUT','Closest baseline: goblet cell has a mucus-filled apical cup; Paneth granules should not be drawn as that cup.')
a('A012','Type II pneumocyte with secretion anchors','Cells','Type II pneumocytes are comparatively compact alveolar epithelial cells that secrete surfactant.','Plan a compact cell cutaway with a nucleus, apical secretion positions and lateral junction anchors. Fit it as a discrete cell in an alveolar wall; expose an apical face toward airspace. Use library vesicles for secretion.','generic epithelial cell;secretory vesicle','resting;secretion-ready','The verified distinction is compact secretory cell versus thin type I cell. Detailed lamellar-body ultrastructure remains outside this specification.','LUNG','Closest baseline: generic epithelial cell; alveolar placement and secretion interfaces motivate this specialized cutaway.')

# Presets reuse existing artwork and never increase the primitive-generation count.
p('P001','Type I pneumocyte placement preset','Cells','Type I pneumocytes form a thin alveolar diffusion surface.','Reuse a flattened epithelial outline with a nucleus bulge and long lateral junction anchors. Apply the type I label only in an alveolar context.','generic epithelial cell;tight junction','extended;alveolar-wall placement','Do not stretch the nucleus with the entire outline; keep cell identity and tissue context explicit.','LUNG','generic epithelial cell')
p('P002','Enterocyte brush-border preset','Cells','Enterocytes have apical microvilli along the intestinal absorptive surface.','Reuse a columnar epithelial cell and place repeated microvilli on its apical face. Preserve a separate nucleus and basal attachment.','columnar epithelial cell;microvilli','isolated;epithelial row','Microvilli are not motile cilia.','GUT','columnar epithelial cell;microvilli')
p('P003','Intestinal endocrine-cell identity preset','Cells','Endocrine cells in intestinal crypts produce gastrointestinal hormones.','Reuse a generic epithelial cell with an endocrine identity label and an optional secretion annotation. Do not create one new silhouette for every hormone.','generic epithelial cell;secretory vesicle','unlabeled archetype;named hormone annotation','The source does not establish a unique silhouette for each endocrine subtype. Detailed polarity requires subtype-specific verification.','GUT','generic epithelial cell')
p('P004','Fenestrated endothelial-cell preset','Cells','Fenestrated capillary endothelium contains pores that support molecular exchange.','Reuse an endothelial cell, with a removable pore-pattern overlay away from the nucleus. Keep the basement membrane as another component.','endothelial cell;basement membrane','continuous;fenestrated overlay','Fenestrae and intercellular gaps are different features; do not make all fenestrated barriers equally permeable.','CAP','endothelial cell')
p('P005','IFNAR1/IFNAR2 identity preset','Immunology','Type I interferon binds a receptor composed of IFNAR1 and IFNAR2.','Reuse the heterodimeric cytokine-receptor archetype; label its chains independently and expose cytosolic partner anchors.','heterodimeric cytokine receptor','unbound;ligand-associated','Chain identity does not justify inventing a new generic receptor drawing.','IFN','heterodimeric cytokine receptor')
p('P006','PD-1 identity preset','Immunology','PD-1 acts as an inhibitory receptor in T-cell signaling.','Reuse the single-pass immunoglobulin-like receptor. Put the binding anchor outside the membrane and the phosphatase-association annotation inside.','single-pass immunoglobulin-like receptor','unligated;ligated;phosphorylation overlay','Use a generic topology unless the precise domain structure is independently checked.','PD1','single-pass immunoglobulin-like receptor')
p('P007','PD-L1 identity preset','Immunology','PD-L1 participates as a PD-1 ligand.','Use a membrane-tethered ligand with a PD-L1 text label, keeping its extracellular binding anchor compatible with P006.','generic membrane-tethered ligand','available;antibody-occupied','A ligand label does not establish exact ectodomain geometry or glycosylation.','PD1','generic membrane-tethered ligand')
p('P008','Signaling kinase identity preset','Signaling','TCR and BCR pathways use named kinases such as LCK, ZAP-70 and SYK.','Reuse the enzyme archetype with independent name and phosphorylation overlays. Expose substrate and recruiter anchors; change labels rather than generate a new blob for each kinase.','generic enzyme','inactive annotation;active annotation;recruited','Activity annotations are context-dependent; color alone must not imply activation.','TCR;BCR','generic enzyme')
p('P009','Signaling phosphatase identity preset','Signaling','PD-1-associated phosphatases attenuate signaling by dephosphorylation.','Reuse a generic enzyme with SHP-1 or SHP-2 as a label and a catalytic relationship to a selected substrate.','generic enzyme','free;recruited;substrate-associated','A generic phosphatase icon does not specify all downstream targets or exclude alternative mechanisms.','PD1','generic enzyme')
p('P010','STAT/IRF transcription-factor identity preset','Signaling','STAT1, STAT2 and IRF9 participate in type I interferon signaling.','Reuse protein and DNA-bound transcription-factor archetypes with independent labels. Assemble a named complex only when the correct partners are selected.','generic globular protein;transcription factor bound to DNA','cytosolic;nuclear;DNA-associated','Do not confuse STAT1 homodimer with STAT1/STAT2/IRF9 ISGF3.','IFN','generic globular protein')
p('P011','Transferrin with iron occupancy preset','Proteins','Transferrin carries iron and releases it in an acidified endosomal setting.','Use one generic protein instance labeled transferrin with two removable iron-occupancy tokens. Tokens are native circles labeled Fe; they are not drug icons.','generic globular protein','apo;one-site schematic;two-site schematic','The protein outline is an identity schematic, not a verified two-lobe structural depiction.','FERR','generic globular protein')
p('P012','Phosphorylation annotation preset','Signaling','Phosphorylation marks receptor and adaptor states in the selected signaling pathways.','Attach removable P tokens to named domains or tails, with an optional phosphosite label. Preserve the base asset unchanged.','generic globular protein;transmembrane protein','unmodified;phosphorylated','A P token is an annotation. Site and stoichiometry require a cited specific event.','TCR;BCR;INS','generic globular protein')
p('P013','RNA lariat topology preset','Nucleic acids','Splicing generates an intron lariat through a branch-point linkage.','Reuse an RNA strand, arrange a loop with a tail and add a branch-point connector. Keep the loop closure distinguishable from ordinary backbone continuation.','RNA strand','intron attached to downstream exon;released lariat','The branch linkage is not an ordinary 3-prime to 5-prime backbone bond.','SPLICE','RNA strand')
p('P014','Ligand-responsive RNA folding preset','Nucleic acids','Riboswitch ligand binding stabilizes a regulatory RNA conformation.','Reuse an RNA strand and a labeled ligand token. Provide two editable strand arrangements and a marked ligand pocket without asserting a sequence.','RNA strand;small-molecule drug','unbound conformation;bound conformation','The small-molecule asset is a generic symbol relabeled as the chosen metabolite; binding can increase or decrease expression.','RIBO','RNA strand')
p('P015','C3b-opsonized particle preset','Immunology','Surface-associated C3b can promote recognition and phagocytosis of a target.','Reuse a bacterial or particle asset and distribute independently selectable protein tokens labeled C3b along its outside. Keep a clean no-opsonin state.','rod-shaped bacterium;generic globular protein','uncoated;C3b-coated','Token density is qualitative and does not establish complement deposition measurements.','C3','rod-shaped bacterium')
p('P016','Annexin V fluorescent probe preset','Assays','Annexin V binds phosphatidylserine in a calcium-dependent manner.','Reuse a protein archetype with an attached fluorophore marker and an Annexin V label. Provide a lipid-facing binding anchor and separate fluorescence annotation.','generic globular protein;fluorescent dye','free;PS-associated','Annexin positivity alone is not a definitive cell-death classification.','ANNEX','generic globular protein;fluorescent dye')
p('P017','DNA cohesive-end preset','Nucleic acids','Compatible DNA ends permit ligation during restriction cloning.','Reuse duplex and single-strand fragments. Preserve strand direction, show a short overhang and allow explicit complementary sequence labels.','linear DNA fragment;single-stranded DNA','5-prime overhang;3-prime overhang;blunt comparison','Do not imply that all restriction enzymes leave the same kind of overhang.','CLONE','linear DNA fragment')
p('P018','Barcoded surface-protein measurement preset','Assays','Antibody-linked oligonucleotides can encode the identity of a bound surface target.','Reuse the DNA-barcoded antibody. Keep target-binding and barcode endpoints separate and annotate target identity without implying fluorescence detection.','DNA-barcoded antibody','unbound;target-bound;barcode captured','Antibody barcode identity, sample identity and cell barcode are different fields.','FEATURE','DNA-barcoded antibody')

# Composite recipes: independently authored layouts, never flattened replacement artwork.
c('C001','TCR proximal signaling sequence','Immunology','TCR engagement couples CD3 phosphorylation to ZAP-70 recruitment and adaptor signaling.','Place a T-cell membrane opposite a peptide-presenting surface. Anchor TCR/CD3 in the T-cell membrane and peptide-MHC opposite it; put labeled LCK, ZAP-70 and LAT nodes on the cytosolic side. Connect engagement, phosphorylation and recruitment in numbered steps, retaining an unstimulated comparison.','T-cell receptor alpha-beta heterodimer;CD3 complex;peptide-MHC class I complex;plasma membrane segment;preset:P008;preset:P012','resting;engaged;proximal signaling','This is a proximal schematic; CD4/CD8 context and downstream branches must be selected explicitly.','TCR','roadmap:9')
c('C002','BCR recognition to second messengers','Immunology','BCR signaling connects antigen recognition to ITAM kinases and downstream second-messenger pathways.','Use a B-cell outline with one enlarged membrane inset. Place BCR outside-facing, CD79 labels on its signaling partners and SYK/BLNK/PLC-gamma2 inside. Branch a labeled PLC step into DAG at the membrane and IP3 toward an ER calcium-release annotation. Keep ion tokens and pathway arrows editable.','B lymphocyte;B-cell receptor;plasma membrane segment;smooth endoplasmic reticulum;preset:P008;preset:P012','unbound;antigen-engaged;second-messenger response','Antigen valency and calcium dynamics vary. Do not draw every BCR as a permanently crosslinked cluster.','BCR','roadmap:6')
c('C003','Complement initiation and three outcomes','Immunology','Complement initiation routes converge on C3 cleavage and have distinct effector outputs.','Build three labeled initiation lanes merging at a C3 cleavage node. Split the output into C3b surface decoration, soluble inflammatory-fragment labels and a terminal membrane-pore panel. Use existing complement complexes and a particle; do not draw all three outcomes as the same arrow or protein.','complement C1 complex;complement membrane attack complex;preset:P015;plasma membrane segment','initiation;amplification;effector outcomes','Select a consistent C2-fragment naming convention before naming a convertase; historical conventions differ.','C3','roadmap:13')
c('C004','Class I peptide-loading itinerary','Immunology','Class I peptide loading occurs in the ER before surface delivery through the secretory pathway.','Arrange cytosol, ER lumen, Golgi and surface as distinct compartments. Move peptide tokens into the ER, associate them with class I MHC and route the loaded complex through Golgi to membrane. Label the beta-2-microglobulin partner without inventing a new protein silhouette.','MHC class I;peptide-MHC class I complex;linear peptide;rough endoplasmic reticulum;Golgi apparatus;transport vesicle;plasma membrane segment','unloaded;ER-loaded;surface-presented','This is the conventional loading route, not a complete description of cross-presentation.','MHCI','roadmap:8')
c('C005','Class II invariant-chain and peptide exchange','Immunology','Endosomal antigen processing and peptide exchange produce surface class II peptide complexes.','Place incoming antigen in an endocytic lane and class II/invariant-chain in a secretory lane. Merge in an acidic compartment; use removable labels for invariant-chain processing and CLIP exchange. Deliver the loaded class II complex to the surface facing a CD4 T-cell receptor panel.','MHC class II;peptide-MHC class II complex;late endosome;lysosome;linear peptide;CD4 receptor;T-cell receptor alpha-beta heterodimer','invariant-chain associated;CLIP-bearing;peptide-loaded','The invariant chain and CLIP are different states; do not show extracellular antigen loading directly onto ER class II as the default route.','MHCII','roadmap:8')
c('C006','Modular full IgE schematic','Immunology','IgE combines antigen-binding arms with an Fc region structurally distinct from IgG Fc.','Attach two existing Fab instances to the planned IgE Fc module, preserving each arm as a linked component. Provide antigen-facing endpoints and an Fc receptor-facing endpoint. Label the result a schematic; do not claim a complete crystallographic pose.','antibody Fab fragment;new:A004','unbound;antigen-associated placeholder','The Fc deposition verifies Fc architecture, not a universal whole-antibody arm angle.','IGEF','', 'P1')
c('C007','Allergen-triggered mast-cell degranulation','Immunology','Aggregation of IgE-bound Fc epsilon receptors can trigger mast-cell mediator release.','Use a mast-cell cutaway with membrane receptor instances and modular IgE outside. A multivalent allergen token bridges receptor-associated IgE; inside, connect a SYK/PLC/calcium annotation to separate granules and exocytosis arrows. Provide sensitized and activated panels.','mast cell;single-pass immunoglobulin-like receptor;secretory vesicle;composite:C006;preset:P008','sensitized;crosslinked;degranulating','Receptor subunits are named schematic groups; do not equate unbound soluble IgE with receptor crosslinking.','IGE','roadmap:15')
c('C008','PD-1 inhibitory contact','Immunology','PD-1 ligation recruits phosphatases that attenuate T-cell signaling.','Place a T-cell membrane opposite a ligand-bearing membrane. Align PD-1 with PD-L1 across the gap, recruit a SHP-labeled enzyme inside the T cell and draw an inhibitory connector to a named proximal signaling node. Keep ligand occupancy and inhibition as separate annotations.','plasma membrane segment;preset:P006;preset:P007;preset:P009;T-cell receptor alpha-beta heterodimer','unligated;ligated;phosphatase recruited','Checkpoint engagement is not a binary guarantee of cell inactivity; a blockade panel would need a specific intervention source.','PD1','roadmap:17')
c('C009','Type I interferon receptor-to-nucleus response','Immunology','Type I interferon signaling produces the STAT1/STAT2/IRF9 complex ISGF3.','Place one IFN ligand above IFNAR1/2. Attach JAK1 and TYK2 labels inside, then show separate STAT1, STAT2 and IRF9 instances assembling into a named group. Route that group through a nuclear boundary to a DNA-response annotation.','small globular cytokine;preset:P005;preset:P008;preset:P010;nucleus;DNA double helix','ligand-free;receptor-active;ISGF3 nuclear','Do not substitute a STAT1 homodimer for ISGF3 or imply every interferon uses this receptor.','IFN')
c('C010','Canonical WNT on/off comparison','Signaling','Canonical WNT stabilizes beta-catenin and changes its transcriptional role.','Create matched WNT-absent and WNT-present panels using the same membrane, Frizzled and nucleus. In the absent panel group Axin/APC/CK1/GSK3 labels around beta-catenin and route turnover to proteasome. In the present panel annotate LRP5/6 with Frizzled and route stabilized beta-catenin to LEF/TCF at DNA.','Frizzled receptor;transmembrane protein;generic globular protein;generic enzyme;proteasome;nucleus;DNA double helix','WNT absent;canonical response','Noncanonical WNT pathways are outside this recipe; generic protein nodes are not verified domain structures.','WNT')
c('C011','Neighbor-dependent NOTCH cleavage','Signaling','A membrane ligand on a neighboring cell triggers NOTCH cleavage and nuclear NICD signaling.','Place two adjacent cell membranes with ligand and Notch facing across the intercellular space. Mark extracellular and intramembrane cleavage as separate steps; detach an NICD-labeled token on the receiving cell side and route it to an RBPJ/MAML-labeled nuclear group.','Notch receptor;generic membrane-tethered ligand;plasma membrane segment;generic globular protein;nucleus','neighbor contact;cleavage;NICD nuclear','Keep the ligand membrane-bound and avoid depicting NICD as the entire intact receptor entering the nucleus.','NOTCH')
c('C012','Insulin receptor activation and attenuation','Signaling','Insulin-receptor phosphorylation recruits signaling pathways; internalization participates in attenuation.','Use matched surface and internalized receptor groups. Bind a labeled insulin token to the receptor, add cytosolic phosphorylation labels and branch to IRS and SHC nodes. Route an internalization arrow into a separate endosomal receptor state; retain an attenuation label rather than erasing every downstream event.','receptor tyrosine kinase dimer;linear peptide;preset:P012;generic globular protein;early endosome','unbound;phosphorylated;internalized','The generic receptor is a schematic; insulin receptor preassembly must not be drawn as ligand-induced dimerization of free monomers.','INS','roadmap:31')
c('C013','Mitochondrial commitment to intrinsic apoptosis','Cell biology','BCL-2-family control links cellular stress to mitochondrial release of apoptotic factors.','Place stress inputs beside a mitochondrion. Add BAX/BAK and anti-apoptotic regulator labels at the outer membrane, then a release arrow to cytochrome-c and an existing apoptosome group. Continue to a named caspase annotation and an apoptotic cell state.','mitochondrion;generic globular protein;apoptosome;apoptotic cell','restrained;outer-membrane permeabilization;downstream response','Keep outer and inner mitochondrial membranes distinct. This omits other death pathways and does not assert a universal irreversible threshold.','APOP','roadmap:34')
c('C014','Cargo enclosure and autolysosome formation','Cell biology','Macroautophagy encloses cargo before fusion with the lysosomal system.','Use the existing autophagosome as the closed state; construct an open double-membrane cup from membrane components for the preceding state. Place a cargo group inside, seal the cup and connect the resulting vesicle to a lysosome/autolysosome endpoint. Maintain two membrane contours at enclosure.','lipid bilayer cross-section;autophagosome;lysosome;generic globular protein','open phagophore;sealed autophagosome;autolysosome','An autophagosome is not a single-membrane endosome. Cargo-receptor specificity requires a separate source.','AUTO','roadmap:63')
c('C015','Ferritin shell and iron-core loading','Structural biology','Ferritin stores iron inside a protein shell.','Reuse the planned shell in matched empty and loaded states. Place independent iron-core fill and Fe tokens inside its cavity, add a qualitative storage arrow and keep the cutaway aperture distinct from a biological pore.','new:A001','empty;partly illustrated core;loaded cutaway','Fill fraction is illustrative, not a calibrated iron concentration or an exact uptake mechanism.','FERR')
c('C016','Transferrin uptake and receptor recycling','Cell biology','Transferrin releases iron after receptor-mediated uptake into an acidified endosomal setting.','Arrange plasma membrane, endosome and a return lane. Bind iron-bearing transferrin to a receptor token, internalize the group, detach iron tokens under an acidification label, then return receptor and apo-transferrin to the surface for release.','preset:P011;transmembrane protein;plasma membrane segment;early endosome','surface-bound;acidic release;recycled','The receptor token is topology-neutral and must be labeled; no particular receptor structure or iron-export machinery is claimed.','FERR')
c('C017','Fibrinogen cleavage to editable fibrin network','Extracellular matrix','Thrombin cleavage enables fibrin assembly into fibers.','Start with a few linked fibrinogen instances and a thrombin-labeled enzyme. Use cleavage annotations followed by an assembly arrow to existing fibrin fibers. Build the final mesh from repeated fibers with explicit junctions, optionally placing platelets within the network as another layer.','new:A002;generic enzyme;fibrin fiber;platelet','soluble precursor;cleavage;network','A network illustration does not specify polymerization kinetics or crosslink chemistry.','FIB','blood clot with platelets and fibrin')
c('C018','Platelet activation and recruitment loop','Hematology','Platelet agonists amplify recruitment and aggregation after activation.','Lay out resting and activated platelets along a vessel-wall context. Release labeled ADP/ATP tokens from the activated group, route them to neighboring platelet receptors and close a positive-feedback arrow. Keep alpha-IIb/beta-3 labels attached to integrin instances in an aggregation inset.','platelet;endothelial monolayer;ADP;ATP;integrin alpha-beta heterodimer','resting;activated;recruiting','Do not present the feedback loop as the full coagulation cascade or assign unsupported clotting-factor complexes.','PLT','blood clot with platelets and fibrin')
c('C019','Membrane protein in a nanodisc','Structural biology','A scaffold belt stabilizes a small bilayer disc that can hold a membrane protein.','Arrange lipid instances into a bilayer patch, wrap its hydrophobic edge with the planned scaffold belt and insert an existing transmembrane protein through the patch. Provide top and tilted side views with individually selectable belt, lipids and protein.','new:A007;lipid bilayer cross-section;transmembrane protein','empty disc;protein-containing disc','Protein copy number, belt count and dimensions remain configurable; this is not a claim about a specific preparation.','NANO','', 'P1')
c('C020','Riboswitch ligand-dependent state comparison','Nucleic acids','Ligand binding can stabilize a regulatory RNA fold and alter gene expression.','Duplicate the same RNA preset into unbound and bound panels. Keep ligand identity and the expression-platform region labeled. Use an editable output badge reading increased or decreased expression only after the chosen riboswitch class is specified.','preset:P014;messenger RNA','unbound;ligand-bound','No universal ON direction is implied; a particular terminator or ribosome-binding-site mechanism needs additional verification.','RIBO')
c('C021','Telomerase repeat-extension cycle','Nucleic acids','Telomerase uses an internal RNA template to extend a telomeric DNA end.','Place the DNA 3-prime end against an RNA-containing protein group labeled telomerase. Align a short RNA template region with the extension site; show repeat addition and repositioning as separate arrows. Preserve DNA/RNA identities and strand-end labels throughout.','telomere;single-stranded DNA;RNA strand;generic globular protein;nucleotide','aligned;extended;repositioned','Sequence labels and repeat length must specify organism; the overview does not model complete telomere replication.','TELO','roadmap:55')
c('C022','Telomeric overhang versus quadruplex state','Nucleic acids','Guanine-rich telomeric DNA can form quadruplex structures.','Reuse one telomere context and replace only its exposed overhang state with the planned G-quadruplex module. Use a reversible state connector and retain strand endpoints. Keep optional shelterin labels outside the fold instead of embedding all telomere proteins in one icon.','telomere;single-stranded DNA;new:A008','extended overhang;quadruplex schematic','Do not portray quadruplex folding as obligatory at all chromosome ends.','TELO','roadmap:55')
c('C023','Spliceosomal branch formation and exon joining','Nucleic acids','Spliceosomal chemistry forms an intron lariat and joins the flanking exons.','Represent two exon blocks connected by an intron strand. Place the existing spliceosome around the junction and mark the branch point. Step one forms a loop linked to the downstream exon; step two joins exons and releases the lariat preset. Preserve exon colors between states.','spliceosome;RNA strand;messenger RNA;preset:P013','pre-mRNA;branched intermediate;joined exons and lariat','This depicts the major spliceosome pathway; branch linkage must not look like an ordinary backbone continuation.','SPLICE','roadmap:27')
c('C024','Four-way DNA junction conformation comparison','Nucleic acids','Four-way DNA junction geometry can vary with sequence and conditions.','Instantiate the same four-arm topology twice, once open for explanation and once stacked. Use consistent strand colors across the views, with labeled arm endpoints. Connect views using a conformation arrow, not a cleavage arrow.','new:A009;DNA double helix','open explanatory view;stacked view','The deposited structure supports a particular stacked geometry; an open depiction is a teaching layout, not a second measured structure.','HJ','roadmap:36')
c('C025','Restriction cloning with orientation check','Methods','Compatible ends enable ligation, while screening is needed to verify the resulting construct.','Arrange donor, cut insert and opened recipient plasmid in parallel lanes; match end labels before joining. Follow ligation with transformation and a separate verification checkpoint. Keep incorrect orientation as an optional clearly marked alternative, not a successful endpoint.','circular plasmid DNA;linear DNA fragment;preset:P017;generic enzyme;bacterial colony on agar;DNA electrophoresis gel with bands','donor and recipient;compatible ends;candidate clone;verified construct','Colony growth alone is not construct verification; this diagram is a conceptual workflow, not an operational protocol.','CLONE')
c('C026','Overlap-based Gibson assembly mechanism','Methods','Gibson assembly combines exonuclease, polymerase and ligase activities on overlapping fragments.','Place color-coded fragments with matched overlap labels. Show exposed complementary regions after end processing, annealing, gap filling and nick sealing as four distinct states. Retain the same fragment colors in the assembled product and show circularization only for a circular design.','linear DNA fragment;single-stranded DNA;generic enzyme;circular plasmid DNA','overlap design;annealed;filled;sealed','Overlaps are designed homology, not arbitrary restriction overhangs; no reaction conditions are specified.','GIBSON')
c('C027','Type IIS ordered assembly logic','Methods','Golden Gate assembly uses cleavage outside recognition sites to produce designed ligation ends.','Use several color-coded DNA modules with separate recognition-site and overhang labels. Draw cleavage outside each recognition site, then order fragments by compatible ends. Keep removed recognition regions visibly excluded from the intended joined product.','linear DNA fragment;preset:P017;generic enzyme;circular plasmid DNA','site-bearing modules;cut modules;ordered product','Directionality depends on the chosen overhang design; do not imply every arbitrary mixture self-orders.','GOLD')
c('C028','Single-cell ATAC partition and library workflow','Single-cell methods','The described single-cell ATAC workflow transposes nuclei before partitioning.','Start with nuclei and a transposition step outside droplets. Then partition with a barcoded bead, connect barcode incorporation to indexed library fragments and end with a sequencing/read-assignment panel. Label empty and multiplet partitions as possible states.','nucleus;transposase-DNA complex;single-cell droplet with barcoded bead;barcoded capture bead;indexed DNA library fragment;sequencing flow cell','bulk transposition;partitioning;barcoded library','One partition barcode does not guarantee one biological cell. The order is specific to the cited assay generation.','ATAC','roadmap:56')
c('C029','Joint RNA and antibody-tag measurement','Single-cell methods','Antibody oligonucleotide tags can be measured alongside gene expression in a single-cell workflow.','Place a surface-bound barcoded antibody on a cell, then put the cell and a capture bead in a partition. Split output into RNA-derived library and antibody-tag library while retaining a common cell-barcode label. Use distinct colors and labels for feature identity versus cell identity.','rounded suspension cell;preset:P018;single-cell droplet with barcoded bead;messenger RNA;indexed DNA library fragment','labeled cells;partition;two linked measurements','A tag count is assay evidence, not an exact molecule count or proof of target function.','FEATURE','roadmap:56')
c('C030','Captured guide identity linked to transcriptome','Single-cell methods','Captured CRISPR guide identities can be linked to single-cell gene-expression data.','Show a cell with a guide-RNA label, a partition and two output tracks: guide identity and transcriptome. Join tracks with the shared cell-barcode field. End with an association panel, leaving perturbation efficacy as a separate validation badge.','guide RNA;rounded suspension cell;single-cell droplet with barcoded bead;messenger RNA;barcoded oligonucleotide','guide-bearing cell;captured identity;linked readouts','Guide detection does not establish successful editing or prove that an observed expression change is causal.','FEATURE','roadmap:56')
c('C031','Sample multiplexing with distinct barcode roles','Single-cell methods','Sample tags add sample identity to single-cell measurements.','Give each input sample a distinct tag label, pool the cell groups and route them into partitions. At output show separate fields for sample tag, cell barcode and feature identity; include ambiguous-tag assignments as unresolved.','cell hashing antibody-tag complex;rounded suspension cell;single-cell droplet with barcoded bead;barcoded oligonucleotide','separate samples;pooled;assigned or ambiguous','Do not conflate a sample tag with a unique cell barcode or assume every cell has a clean sample assignment.','FEATURE','roadmap:56')
c('C032','Annexin and membrane-integrity interpretation panel','Assays','Annexin V reports accessible phosphatidylserine; membrane damage affects interpretation.','Build a membrane inset with PS labels and a calcium-dependent Annexin probe. Pair it with a membrane-impermeant-dye annotation and an editable two-axis schematic. Label quadrants by measured positivity first; annotate double positivity as compatible with late apoptotic or other dead cells.','plasma membrane segment;phospholipid;preset:P016;fluorescent dye;apoptotic cell;necrotic cell','Annexin negative or positive;integrity-dye negative or positive','Do not label every double-positive cell late apoptotic or treat Annexin alone as a definitive death assay.','ANNEX','roadmap:104')
c('C033','Intestinal crypt epithelial composition','Tissue biology','Intestinal crypts contain multiple epithelial cell types including Paneth and endocrine cells.','Use the crypt as a context frame. Place repeated epithelial instances along its wall, Paneth cells at the base and independently labeled endocrine and goblet cells among them. Keep the lumen unobstructed and cell identities selectable.','intestinal crypt;columnar epithelial cell;goblet cell;new:A011;preset:P003','overview;cell-type inset','This is a composition map, not a validated stem-cell lineage trajectory or a quantitative cell-frequency chart.','GUT','roadmap:88')
c('C034','Villus exchange routes and brush border','Tissue biology','Villi combine an absorptive epithelium with blood and lymphatic vessels.','Use a villus context and add an enlarged apical brush-border inset from enterocyte presets. Draw separate capillary and lacteal paths inside the villus, with labels rather than an undifferentiated vascular tube. Keep lumen-to-epithelium direction clear.','intestinal villus;preset:P002;goblet cell;capillary cross-section;lymphatic vessel','whole villus;surface inset','Nutrient-specific transporters and blood-versus-lymph routing need additional substrate-specific evidence.','GUT','roadmap:88')
c('C035','Alveolar air-blood diffusion barrier','Tissue biology','Thin alveolar epithelium and capillary endothelium form the gas-exchange interface.','Build an alveolar wall from flattened type I presets, basement-membrane components and endothelial cells. Place airspace on one side and erythrocytes in a capillary lumen on the other. Add independent O2 and CO2 arrows with opposing directions across the barrier.','alveolus;preset:P001;basement membrane;endothelial cell;erythrocyte','tissue view;barrier inset','Widths and distances are schematic; do not represent cell layers as equal-thickness slabs or claim a measured diffusion rate.','LUNG','roadmap:87')
c('C036','Type II cell surfactant secretion context','Tissue biology','Type II pneumocytes secrete surfactant toward the alveolar airspace.','Place the planned type II cell among type I cell presets. Orient secretion anchors toward the airspace; move separate vesicle instances toward that face and add a surface-film annotation. Keep the surfactant layer distinct from the basement membrane below the cells.','new:A012;preset:P001;secretory vesicle;alveolus','stored secretion;apical release;surface film','The film is a symbolic overlay; molecular surfactant composition and lamellar-body detail are not specified.','LUNG','roadmap:87')
c('C037','Capillary wall architecture comparison','Tissue biology','Continuous, fenestrated and sinusoidal capillary architectures differ.','Create three matched vessel cross-section panels with consistent lumen orientation. Reuse endothelial and basement-membrane components; add fenestrae as intracellular pore overlays and sinusoidal discontinuities as a separately labeled pattern. Use an optional external pericyte only in the appropriate contextual panel.','capillary cross-section;endothelial cell;preset:P004;basement membrane;new:A010','continuous;fenestrated;sinusoidal','Do not generalize pore sizes, basement-membrane continuity or permeability to every organ from the generic panels.','CAP','roadmap:86')
c('C038','Pericyte-endothelial spatial relationship','Tissue biology','Pericytes associate with the abluminal side of capillary endothelium.','Use a short endothelial tube or existing vessel context and place pericyte processes along its exterior. Add a cutaway showing lumen, endothelial layer and exterior cell contact. Keep pericyte and endothelium as different selectable cell groups.','small blood vessel;endothelial cell;new:A010;basement membrane','longitudinal view;cross-section inset','This establishes location, not a universal pericyte coverage fraction or molecular signaling mechanism.','CAP','roadmap:85')
c('C039','Outer-membrane porin diffusion and reduced access','Microbiology','Porins provide diffusion paths; reduced permeability can contribute to resistance.','Insert porin instances into the outer membrane of the Gram-negative envelope. Route a labeled compatible solute through the lumen into periplasm in one panel; reduce channel availability or show restricted passage in the comparison. Keep the inner membrane separate and do not add an ATP-consumption arrow.','Gram-negative cell-envelope cross-section;new:A005;small-molecule drug','permeable schematic;reduced-access schematic','Permeability effects depend on compound and porin. Reduced entry does not by itself prove clinical antibiotic resistance.','PORIN','roadmap:84')
c('C040','LPS position in a Gram-negative envelope','Microbiology','LPS combines lipid anchoring with carbohydrate regions at the bacterial surface.','Reuse the Gram-negative envelope frame and attach LPS lipid regions into the outer-facing membrane leaflet. Extend carbohydrate chains toward the extracellular side, leaving periplasm and inner membrane distinct. Use variable chain lengths as qualitative variants.','Gram-negative cell-envelope cross-section;new:A003','short carbohydrate schematic;extended carbohydrate schematic','Carbohydrate composition varies; do not call every generic chain a specific bacterial serotype.','LPS','roadmap:72')
c('C041','Aggrecan-collagen cartilage matrix organization','Extracellular matrix','Aggrecan and collagen contribute different structural features to cartilage matrix.','Place aggrecan brush instances between collagen fibrils around a chondrocyte context. Keep collagen, aggrecan cores and side chains as separate groups. Offer intact and reduced-aggrecan illustrative states with identical layout for comparison.','new:A006;collagen fibril;chondrocyte;extracellular matrix mesh','organized matrix;reduced-aggrecan comparison','Do not infer stiffness values, disease severity or a specific degradation enzyme from the schematic density.','AGG','roadmap:99')
c('C042','STING trafficking to interferon-response signaling','Immunology','STING signaling involves a localization change and TBK1/IRF3-dependent response.','Place a STING-labeled membrane protein at ER, add a trafficking arrow toward a Golgi/perinuclear state and connect TBK1 and IRF3 labels to a nuclear response annotation. Keep activation input as an explicitly unspecified upstream node.','smooth endoplasmic reticulum;Golgi apparatus;transmembrane protein;generic enzyme;generic globular protein;nucleus','ER-localized;trafficked;downstream response','This source mixes historical human and mouse evidence. A cGAS/cGAMP mechanism or species-specific residues require a newer targeted source.','STING')

B=[]
def b(id,name,category,proposal,components,check,related):
    B.append(dict(id=id,kind='brainstorm',name=name,category=category,design_proposal=proposal,component_names=components.split(';'),verification='brainstorm_not_source_verified',required_verification=check,related_baseline=related,novelty='specialized_recipe_candidate',design_status='proposed_not_generated'))
b('B001','Stomatal opening and closing comparison','Plant biology','Reuse guard cells and a leaf-surface frame in matched open and closed states; add independent water/ion annotations rather than deforming the entire leaf.','stomatal guard-cell pair;leaf','Verify guard-cell geometry, ion transport and the selected environmental response in an authoritative plant source.','stomatal guard-cell pair')
b('B002','Root radial water-transport routes','Plant biology','Construct a layered root cross-section using plant cells and wall segments; distinguish wall-space and cytoplasmic routes with separate connectors.','root hair cell;generic plant cell;plant cell wall segment','Verify endodermal barrier placement, route definitions and which new topology components are actually needed.','root system')
b('B003','Source-to-sink phloem transport','Plant biology','Connect a source leaf and a sink organ through a clearly labeled vascular path, using editable loading and unloading insets.','leaf;root system;seed;generic plant cell','Verify transport model and tissue anatomy; sieve elements may need a genuinely distinct building block.','root system')
b('B004','Thylakoid electron-transfer map','Plant biology','Use the chloroplast context and a membrane inset with labeled protein nodes, electron arrows and a separate proton path.','chloroplast;lipid bilayer cross-section;ATP synthase;generic globular protein','Verify photosystem order, membrane sides and proton stoichiometry before adding quantitative labels.','roadmap:59')
b('B005','Mycorrhizal root interface','Plant biology','Place fungal hyphae beside a root cell context and use separate nutrient-exchange arrows across a labeled interface.','filamentous fungal hypha;root hair cell;generic plant cell','Select arbuscular or ectomycorrhizal organization; verify the relevant interface rather than blending the two.','root system')
b('B006','Pollen tube guidance to an ovule','Development','Reuse pollen and floral context with an editable tube path and destination inset.','pollen grain;flower;generic plant cell','Verify tissue geometry and fertilization stages; identify whether tube or ovule topology is missing.','flower')
b('B007','Bacterial sporulation stage sequence','Microbiology','Reuse a rod bacterium and spore in successive compartment states; make septum and envelope overlays independently editable.','rod-shaped bacterium;bacterial endospore;plasma membrane segment','Verify species-specific septation, engulfment and coat order.','bacterial endospore')
b('B008','Asymmetric yeast budding and separation','Microbiology','Arrange linked yeast instances across bud emergence, growth and separation; preserve mother/bud identity across panels.','budding yeast cell;nucleus;actin filament','Verify nuclear segregation and cell-wall remodeling events for a chosen organism.','budding yeast cell')
b('B009','Biofilm dispersal versus growth','Microbiology','Reuse bacterial groups and extracellular matrix in two panels; release a subset into a separate planktonic lane.','bacterial biofilm microcolony;rod-shaped bacterium;extracellular DNA web','Verify dispersal triggers and matrix composition for a specified biofilm model.','roadmap:76')
b('B010','Conjugative DNA transfer and establishment','Microbiology','Use the existing conjugation pair and a plasmid inset to distinguish donor DNA, transferred strand and recipient establishment.','bacterial conjugation pair with pilus;circular plasmid DNA;single-stranded DNA','Verify strand processing, transfer direction and replication stages for a selected plasmid system.','roadmap:75')
b('B011','Bacterial efflux versus reduced entry','Microbiology','Build matched cell-envelope panels separating outward active transport from inward permeability changes.','Gram-negative cell-envelope cross-section;ABC transporter;small-molecule drug','Verify the chosen pump family; do not substitute an ABC transporter for every efflux mechanism.','roadmap:84')
b('B012','Phage lytic and lysogenic decision diagram','Microbiology','Branch the existing phage/host context into replicated-particle production and integrated-genome maintenance states.','bacteriophage;rod-shaped bacterium;viral DNA genome;DNA double helix','Choose a temperate phage and verify integration, induction and lifecycle boundaries.','roadmap:78')
b('B013','Antibody class-switch DNA rearrangement','Immunology','Use a labeled DNA locus and a B-cell context, keeping variable-region identity separate from constant-region replacement.','B lymphocyte;DNA double helix;generic IgG antibody;IgM pentamer','Verify switch-region topology and distinguish class switching from somatic hypermutation.','B lymphocyte')
b('B014','Germinal-center selection itinerary','Immunology','Arrange linked B-cell states and helper-cell contacts inside a lymphoid context, with explicit movement and selection connectors.','B lymphocyte;T lymphocyte;lymph node cross-section;antigen-antibody immune complex','Verify light/dark zone roles and whether follicular dendritic-cell morphology is a missing primitive.','lymph node cross-section')
b('B015','Leukocyte rolling to arrest under flow','Immunology','Reuse an endothelial strip and leukocyte instances, with selectin and integrin insets linked to sequential movement states.','endothelial monolayer;neutrophil;selectin;integrin alpha-beta heterodimer','Verify receptor-ligand pairs, affinity states and the selected leukocyte context.','roadmap:23')
b('B016','Efferocytosis recognition and resolution','Immunology','Place apoptotic-body instances beside a macrophage, then use linked engulfment and post-engulfment annotation panels.','apoptotic body;macrophage;phagosome;phospholipid','Verify recognition bridges and downstream response; keep this distinct from microbial phagocytosis.','roadmap:11')
b('B017','NK activating and inhibitory signal balance','Immunology','Use an NK/target contact with independent activating and inhibitory receptor lanes and a configurable output annotation.','natural killer cell;generic cancer cell;MHC class I;single-pass immunoglobulin-like receptor','Verify receptor specificity and licensing context; avoid a deterministic missing-self cartoon.','roadmap:10')
b('B018','Innate-cell inflammasome and gasdermin output','Immunology','Reuse an inflammasome and a membrane inset, separating assembly, protease activation and membrane-pore output.','inflammasome complex;generic enzyme;plasma membrane segment','Verify inflammasome type, caspase and gasdermin cleavage; assess whether a gasdermin pore needs a new module.','roadmap:21;roadmap:33')
b('B019','ER protein quality-control routing','Cell biology','Place folded and unresolved protein presets inside an ER context with distinct forward-transport and degradation lanes.','rough endoplasmic reticulum;generic globular protein;ubiquitinated protein;proteasome','Verify ER-associated degradation direction, membrane extraction and chaperone roles.','roadmap:26')
b('B020','Organelle contact-site lipid exchange','Cell biology','Place ER and mitochondrion in close proximity with an explicit gap and exchange connectors, keeping their membranes unfused.','smooth endoplasmic reticulum;mitochondrion;phospholipid','Verify contact-site tether and lipid-transfer mechanism; proximity must not imply membrane fusion.','roadmap:58')
b('B021','Stress granule assembly and recovery','Cell biology','Use RNA/protein instances to populate a reversible granule group, with a separate resumed-translation panel.','stress granule;messenger RNA;generic globular protein;ribosome translating mRNA','Verify stress context and distinguish a qualitative condensate diagram from measured phase separation.','stress granule')
b('B022','Receptor recycling versus lysosomal sorting','Cell biology','Split an internalized receptor lane into surface return and lysosomal delivery while preserving cargo identity.','early endosome;late endosome;lysosome;transmembrane protein;transport vesicle','Verify sorting signals and named receptor behavior; avoid assigning one fate to all receptors.','roadmap:61')
b('B023','Mitochondrial fission and fusion comparison','Cell biology','Use linked mitochondrion states with separate constriction and joining sequences; keep inner/outer membranes distinguishable.','mitochondrion;generic globular protein;lipid bilayer cross-section','Verify machinery and membrane order; do not equate all fragmentation with apoptosis.','roadmap:58')
b('B024','Axonal conduction across myelin gaps','Neurobiology','Repeat myelin segments around an axon and label nodes, with a distinct propagation annotation above the structure.','isolated axon;myelin sheath;node of Ranvier;voltage-gated ion channel','Verify ion-channel localization and the chosen electrophysiological abstraction.','node of Ranvier')
b('B025','Astrocyte-neuron metabolic exchange','Neurobiology','Place an astrocyte and neuron in a tissue context with labeled metabolite-transfer arrows that can be toggled by hypothesis.','astrocyte;neuron;glucose;small blood vessel','Verify each metabolite route and distinguish supported observations from contested shuttle models.','roadmap:95')
b('B026','Glomerular filtration barrier layers','Tissue biology','Build a cutaway from endothelium, basement membrane and podocyte processes, with a separate filtrate-side label.','renal glomerulus;endothelial cell;basement membrane;podocyte','Verify layer order, slit diaphragm and filtration-selectivity claims; do not infer selectivity from icon size alone.','roadmap:89')
b('B027','Bone remodeling coupling','Tissue biology','Arrange resorption and formation regions along one bone surface using osteoclast and osteoblast instances.','bone trabecula;osteoclast;osteoblast;osteocyte','Verify temporal coupling and matrix deposition; mineralization is a distinct stage.','roadmap:92')
b('B028','Hepatic lobule directional flows','Tissue biology','Overlay separate blood and bile routes on a reusable lobule frame with unambiguous directions and endpoints.','liver lobule;hepatocyte;small blood vessel','Verify portal/central anatomy and canalicular bile direction; identify missing duct components.','roadmap:90')
b('B029','Transwell migration with counting endpoint','Methods','Place cells above a porous insert, directional cues below and migrated cells in a separately countable lower compartment.','Transwell insert;porous membrane insert;rounded suspension cell;chemokine','Verify assay configuration and distinguish migration from proliferation or differential survival.','Transwell insert')
b('B030','Magnetic enrichment with retained and depleted fractions','Methods','Use antibody-bead-cell groups passing a magnetic column, retaining both output fractions with explicit labels.','magnetic-bead-cell complex;magnetic separation column;cell-sort collection tube rack','Verify positive versus negative selection and recovery sequence; purity is measured, not implied.','magnetic separation column')
b('B031','Organoid passage and recovery overview','Methods','Arrange source organoid, separated material and regrowing groups in culture contexts with an independent viability checkpoint.','organoid;extracellular matrix gel dome;cell culture plate' .replace('cell culture plate','24-well plate'),'Choose an organoid system and verify whether fragmentation or dissociation is appropriate.','roadmap:116')
b('B032','Perfused organ-on-chip barrier measurement','Methods','Build two channels separated by a cell-covered porous membrane; add independent perfusion and sampling connectors.','organ-on-chip device;porous membrane chip;endothelial monolayer;perfusion pump','Verify channel orientation, flow regime and readout; do not invent a permeability value.','organ-on-chip device')
b('B033','Spatial spot mixtures versus individual cells','Single-cell methods','Overlay capture spots on a tissue frame and show several cell instances intersecting a spot, followed by an explicitly mixed readout.','spatial transcriptomics slide;tissue capture spot array;epithelial sheet','Verify platform resolution and capture model; do not label a multicell spot as a single cell.','roadmap:57')
b('B034','Ambient RNA and multiplet quality-control panel','Single-cell methods','Create empty, singlet and doublet partition scenes with separate ambient RNA tokens and downstream quality-control annotations.','single-cell droplet with barcoded bead;rounded suspension cell;messenger RNA','Verify technical failure modes and limits of computational correction for the chosen assay.','roadmap:56')
b('B035','Surface binding versus internalization assay','Methods','Pair surface-bound probe and intracellular probe panels using the same receptor/ligand group and a time annotation.','transmembrane protein;fluorophore-conjugated antibody;early endosome','Verify controls that distinguish internalization from surface signal; fluorescence location alone may be insufficient.','roadmap:103')
b('B036','Chromatographic separation and fraction identity','Methods','Link a sample mixture to a column, editable elution trace and individual fraction tubes with consistent component colors.','size-exclusion chromatography column;generic globular protein;fraction collector;microcentrifuge tube','Verify separation principle and calibration; elution position is not automatically molecular identity.','size-exclusion chromatography column')

# Remove two redundant recipes: their state comparisons already belong to primitives.
R=[r for r in R if r['id'] not in {'C015','C024'}]

BASE_FILES=['docs/ai-bioart-asset-inventory.md','docs/ai-bioart-asset-inventory-additions.md','docs/assembled-assets-roadmap.md','experiments/ai-assets/nih-bioart-collection/inventory-progress.json']
snapshots=[]
for rel in BASE_FILES:
    expected=subprocess.check_output(['git','show',f'{BASE}:{rel}'],cwd=ROOT)
    actual=(ROOT/rel).read_bytes()
    assert actual==expected, f'Protected baseline changed: {rel}'
    snapshots.append(dict(path=rel,sha256=hashlib.sha256(actual).hexdigest()))
rows=[]
for rel in BASE_FILES[:2]:
    for lineno,line in enumerate((ROOT/rel).read_text().splitlines(),1):
        match=re.match(r'^- \[[ xX]\] (.+)$',line)
        if match: rows.append(dict(name=match[1],path=rel,line=lineno))
assert len(rows)==770
names={r['name'] for r in rows}
assert len(names)==768
progress=json.loads((ROOT/BASE_FILES[3]).read_text())
entries={e['name']:e for e in progress['entries']}
assert names==set(entries), 'Progress and inventory differ'
base_assets={}
collection=ROOT/'experiments/ai-assets/nih-bioart-collection'
for name in sorted(names,key=norm):
    e=entries[name]; item=progress['assets'].get(e['id'],{})
    files={}
    for fmt in ['png','svg']:
        rel=item.get(fmt)
        if rel:
            path=collection/rel
            exists=path.is_file()
            expected=item.get(fmt+'_sha256')
            matches=exists and bool(expected) and hashlib.sha256(path.read_bytes()).hexdigest()==expected
            files[fmt]=dict(path=str(path.relative_to(ROOT)),exists_at_snapshot=exists,sha256_matches_record=matches)
    base_assets[name]=dict(id=e['id'],name=name,category=e['category'],status_at_snapshot=item.get('status','not_recorded'),files=files,inventory_rows=[r for r in rows if r['name']==name])
source_map={s['source_id']:s for s in S}
all_records=R+B
record_map={r['id']:r for r in all_records}
assert len(record_map)==len(all_records)
assert len({norm(r['name']) for r in all_records})==len(all_records)
base_norm={norm(n):n for n in names}
roadmap=(ROOT/BASE_FILES[2]).read_text()
roadmap_items={int(m[1]):m[2] for m in re.finditer(r'^(\d+)\. (.+)$',roadmap,re.M)}
assert len(roadmap_items)==136, len(roadmap_items)
for r in all_records:
    assert norm(r['name']) not in base_norm, f'Exact-name duplicate: {r["name"]}'
    r['components']=[]
    for name in r['component_names']:
        if ':' in name:
            prefix,id=name.split(':',1)
            assert prefix in ['new','preset','composite'] and id in record_map, name
            target=record_map[id]
            expected={'new':'new_primitive','preset':'reuse_preset','composite':'composite'}[prefix]
            assert target['kind']==expected,(name,target['kind'])
            r['components'].append(dict(reference=id,name=target['name'],origin='this_plan',availability='planned_not_generated'))
        else:
            assert name in base_assets, f'{r["id"]}: unknown component {name}'
            item=base_assets[name]
            r['components'].append(dict(reference=item['id'],name=name,origin='baseline_768',status_at_snapshot=item['status_at_snapshot'],files=item['files']))
    for number in re.findall(r'roadmap:(\d+)',r.get('related_baseline','')):
        assert int(number) in roadmap_items,number
    if r['kind']!='brainstorm':
        assert r['source_ids'] and all(x in source_map for x in r['source_ids'])
        assert all(r.get(field) for field in ['scientific_description','design_instructions','scientific_caveat','states','related_baseline'] if field!='related_baseline')
        r['evidence']=[dict(source_id=x,url=source_map[x]['url'],location=source_map[x]['evidence_location']) for x in r['source_ids']]
        r['deduplication_decision']=r['related_baseline'] or 'No matching named primitive or numbered roadmap recipe found in manual topic comparison. This is a new recipe, not a new primitive.'
        if r['kind']=='composite':
            r['assembly_contract']='Instantiate linked component assets; group them with editable transforms, labels and typed connectors. Resolve pending primitives first. Do not generate or flatten the complete scene into a new SVG.'

def visit(id,stack=()):
    assert id not in stack, f'Component dependency cycle: {stack+(id,)}'
    for dep in record_map[id]['components']:
        if dep['origin']=='this_plan': visit(dep['reference'],stack+(id,))
for id in record_map: visit(id)
counts=dict(collection_rows=len(rows),baseline_unique_names=len(names),existing_roadmap_concepts=len(roadmap_items),verified_specs=len(R),new_primitive_candidates=sum(r['kind']=='new_primitive' for r in R),reuse_presets=sum(r['kind']=='reuse_preset' for r in R),composite_recipes=sum(r['kind']=='composite' for r in R),new_composite_topics=sum(r['kind']=='composite' and r['novelty']=='new' for r in R),expanded_existing_composites=sum(r['kind']=='composite' and r['novelty']!='new' for r in R),brainstorm_candidates=len(B),sources=len(S))
dump(OUT/'catalog.json',dict(schema_version=1,date=DATE,baseline_commit=BASE,counts=counts,records=all_records))
dump(OUT/'research/baseline-snapshot.json',dict(commit=BASE,files=snapshots,counts=counts,assets=list(base_assets.values()),roadmap=roadmap_items))
dump(OUT/'research/sources.json',S)

def links(r): return '; '.join(f'[{key}]({source_map[key]["url"]}) ({source_map[key]["evidence_location"]})' for key in r['source_ids'])
def component_text(r):
    return '; '.join(f'`{d["reference"]}` ({d["name"]}; '+(d['status_at_snapshot']+' at baseline' if d['origin']=='baseline_768' else 'planned in this catalog')+')' for d in r['components'])
def render(group,title,intro):
    text=f'# {title}\n\n{intro}\n\n[Catalog guide](README.md) · [Assembly rules](ASSEMBLY-INSTRUCTIONS.md)\n\n'
    for r in group:
        text+=f'## {r["id"]} — {r["name"]}\n\n'
        text+=f'**Category:** {r["category"]}. **Disposition:** {r["novelty"]}.\n\n'
        if r['kind']=='brainstorm':
            text+=f'**Proposed scene:** {r["design_proposal"]}\n\n**Required verification:** {r["required_verification"]}\n\n**Existing coverage:** {r["related_baseline"]}. Expand that concept; do not add a duplicate primitive.\n\n'
        else:
            text+=f'**Verified scientific scope:** {r["scientific_description"]}\n\n**Proposed construction:** {r["design_instructions"]}\n\n**States:** {"; ".join(r["states"])}.\n\n**Limits:** {r["scientific_caveat"]}\n\n**Deduplication:** {r["deduplication_decision"]}\n\n**Evidence:** {links(r)}\n\n'
        text+=f'**Reusable dependencies:** {component_text(r)}.\n\n'
    return text.rstrip()+'\n'
(OUT/'NEW-ASSETS.md').write_text(render([r for r in R if r['kind']=='new_primitive'],'New building-block candidates','12 distinct morphology or topology candidates after comparison with the 768-name baseline. These are planning requests, not permission to generate artwork. First try existing editable geometry; a candidate that can be expressed as a preset should remain a preset.'))
(OUT/'REUSE-PRESETS.md').write_text(render([r for r in R if r['kind']=='reuse_preset'],'Reuse and identity presets','18 configurations of existing artwork. None counts as a new primitive. Labels, state overlays and placement rules carry the specialization.'))
(OUT/'COMPOSITES.md').write_text(render([r for r in R if r['kind']=='composite'],'Composite recipes','40 source-checked schematic recipes. Disposition distinguishes new topics from expansions of existing inventory/roadmap concepts. Every recipe assembles library instances; the recipe itself is not a request for a new full-scene SVG.'))
(OUT/'BRAINSTORM.md').write_text(render(B,'Further asset and recipe ideas','36 independently brainstormed specializations. These have not been source-verified and are not ready for scientific implementation. Each lists the exact check still required and existing library coverage. Do not count them as 36 new primitive assets.'))

ledger_fields=['source_id','bib_key','title','authors','year','family_or_topic','artifact_type','version_or_release_date','url','accessed_date','primary_source','claims_supported','evidence_location','disclosure_status','notes']
with (OUT/'research/source-ledger.csv').open('w',newline='') as f:
    writer=csv.DictWriter(f,fieldnames=ledger_fields,lineterminator='\n');writer.writeheader()
    for s in S:
        supported=[r['id'] for r in R if s['source_id'] in r['source_ids']]
        writer.writerow(dict(source_id=s['source_id'],bib_key=s['source_id'],title=s['title'],authors='Not normalized; use linked source attribution',year='not-disclosed',family_or_topic=s['verified_scope'],artifact_type=s['artifact_type'],version_or_release_date='Live page accessed '+DATE,url=s['url'],accessed_date=DATE,primary_source='yes' if s['artifact_type']=='primary structural deposition' else 'curated reference or official documentation; not necessarily original experimental evidence',claims_supported=';'.join(supported),evidence_location=s['evidence_location'],disclosure_status='reported',notes=s['retrieval']+' Scientific scope only; layouts and priorities are independently proposed. Publication year was not normalized.'))
with (OUT/'research/claim-evidence-matrix.csv').open('w',newline='') as f:
    writer=csv.DictWriter(f,fieldnames=['claim_id','section','claim','source_ids','evidence_location','status','notes'],lineterminator='\n');writer.writeheader()
    for r in R:
        writer.writerow(dict(claim_id=r['id']+'-science',section=r['kind'],claim=r['scientific_description'],source_ids=';'.join(r['source_ids']),evidence_location='; '.join(e['source_id']+': '+e['location'] for e in r['evidence']),status='reported',notes='Verified at schematic scope. Limit: '+r['scientific_caveat']))
        writer.writerow(dict(claim_id=r['id']+'-design',section=r['kind'],claim=r['design_instructions'],source_ids='',evidence_location='Independent planning proposal',status='inferred',notes='Proposed layout, not a reported image or experimentally verified geometry.'))
    for r in B:
        writer.writerow(dict(claim_id=r['id'],section='brainstorm',claim=r['design_proposal'],source_ids='',evidence_location='No source verification performed',status='not-disclosed',notes=r['required_verification']))
report=dict(result='pass',counts=counts,protected_files_byte_identical=True,exact_name_duplicates_with_baseline=0,duplicate_catalog_names=0,all_dependencies_resolve=True,dependency_cycles=0,all_verified_specs_have_sources=True,semantic_review='Manual nearest-archetype and roadmap comparison recorded per entry; normalization alone does not prove semantic uniqueness.',artwork_generated=False)
dump(OUT/'research/validation-report.json',report)
print(json.dumps(report,indent=2))

# Portable bibliography keys match the source ledger; dates not verified stay absent.
bib=[]
for s in S:
    bib.append('@misc{'+s['source_id']+',\n  title = {'+s['title']+'},\n  url = {'+s['url']+'},\n  note = {Accessed '+DATE+'; '+s['artifact_type']+'}\n}')
(OUT/'research/sources.bib').write_text('\n\n'.join(bib)+'\n')
index='# Planning index\n\n[Guide](README.md) · [Assembly instructions](ASSEMBLY-INSTRUCTIONS.md)\n\nNames below are planning specifications, not 106 new primitive assets. Brainstorms require further source verification.\n\n| ID | Description | Category | Disposition |\n|---|---|---|---|\n'
files={'new_primitive':'NEW-ASSETS.md','reuse_preset':'REUSE-PRESETS.md','composite':'COMPOSITES.md','brainstorm':'BRAINSTORM.md'}
for r in all_records:
    index+=f'| {r["id"]} | [{r["name"]}]({files[r["kind"]]}#{r["id"].lower()}) | {r["category"]} | {r["novelty"]} |\n'
for filename in files.values():
    path=OUT/filename
    content=path.read_text()
    content=re.sub(r'^## ([A-Z]\d{3}) —',lambda m:'<a id="'+m[1].lower()+'"></a>\n\n## '+m[1]+' —',content,flags=re.M)
    path.write_text(content)
(OUT/'INDEX.md').write_text(index)
